######################################################################
# Automatically generated by qmake (3.0) Wed Nov 9 15:17:24 2016
######################################################################

QT += core gui opengl testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += . $$PWD/../include /usr/local/include /usr/include /home/idris/dev/include

LIBS += -L/usr/local/lib -L/usr/lib -lGL -lGLU -lGLEW \
        -L${HOME}/dev/lib -L/usr/local/lib -lassimp \

# Input
SOURCES += diffTest.cpp

CONFIG += console c++11